### ISSUE TITLE
Nobody can join at roundstart. Wastes job slots.

### ISSUE THREAD

**Issue by cruxxansata** [Chatter42/AEIOUStation13#123]
#### Brief description of the issue
When someone tries to Ready Up, when the round starts they do not spawn in-game and instead, nothing happens. However, the job slot is consumed as if they had joined.

#### What you expected to happen
For people to be able to hit Ready and not worry about the game eating the job slot while kicking people to the lobby.

#### What actually happened
People can't join at roundstart, everyone *must* latejoin.

#### Steps to reproduce
- New round
- Ready up.
- Watch in awe as your job slot is consumed by the voracious game lobby.

#### Code Revision
- 9bda0e7e03ed37bb20d11e4596025fb80ddfce74 
 
#### Anything else you may wish to add:
n/a

**Comment by drexample** [comment]
Should be fixed by now, need to check in the future

**Comment by drexample** [comment]
Fixed
