### ISSUE TITLE
Languages

### ISSUE THREAD

**Issue by EldritchClown** [Chatter42/AEIOUStation13#85]
#### Brief description of the issue
Common Skrellian and Terminus cannot be spoken. The logic of lacking vocal cords for these things is just silly, imo, because that would mean a LOT of languages need to get limited like this, rather than just the two.

#### What you expected to happen
I would expect at least Akula that are heavily tied to the Skrell to be able to speak it, given that Skrell are canonically the first to encounter them when they were still tribal, and then subsequently helped them out. 

Regarding Terminus and the Zorren, it's their native language, I would expect that to be something they can speak.

#### What actually happened
idk if the rest of these actually need to be filled out at this point or if i need to leave them for you guys because i'm an old man who doesn't know how to use computers

#### Steps to reproduce
- (Step 1)
- (Step 2)
- (and so on)

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by EvilJackCarver** [comment]
Possibly related to commit: https://github.com/Chatter42/AEIOUStation13/commit/edf92c57f9f2ee382c7edaad05ec1c22d3225446

Further research necessary though.

**Comment by EvilJackCarver** [comment]
Possible cause: Skrellian is listed as an assisted language for the species (inheritance issue: https://github.com/Chatter42/AEIOUStation13/blob/master/code/modules/mob/living/carbon/human/species/species.dm )
